--- #YAML:1.0
name:               Dpchrist-TriangularNumber
version:            1.018
abstract:           Perl extension for Triangular numbers.
author:
    - David Paul Christensen dpchrist@holgerdanske.com
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Dpchrist::Debug:   1.042
    Dpchrist::Module:  1.023
    feature:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
